CREATE TABLE [Staging].[CashbackTransaction] (
    [Id]                      INT             IDENTITY (1, 1) NOT NULL,
    [TransactionFileId]       INT             NOT NULL,
    [ResultsId]               NVARCHAR (300)  NULL,
    [SourceId]                NVARCHAR (300)  NULL,
    [NetworkId]               NVARCHAR (300)  NULL,
    [NetworkName]             NVARCHAR (300)  NULL,
    [ConnectionId]            NVARCHAR (300)  NULL,
    [MerchantId]              NVARCHAR (300)  NULL,
    [MerchantName]            NVARCHAR (300)  NULL,
    [OrderId]                 NVARCHAR (300)  NULL,
    [Country]                 NVARCHAR (3)    NULL,
    [Clicked]                 DATETIME2 (7)   NULL,
    [Sold]                    DATETIME2 (7)   NULL,
    [Checked]                 DATETIME2 (7)   NULL,
    [Referrer]                NVARCHAR (300)  NULL,
    [BasketId]                NVARCHAR (300)  NULL,
    [BaskedSourceId]          NVARCHAR (300)  NULL,
    [Name]                    NVARCHAR (300)  NULL,
    [Currency]                NVARCHAR (10)   NULL,
    [PriceTotal]              DECIMAL (18, 2) NOT NULL,
    [Revenue]                 DECIMAL (18, 2) NOT NULL,
    [SourcePriceTotal]        DECIMAL (18, 2) NOT NULL,
    [SourceRevenue]           DECIMAL (18, 2) NOT NULL,
    [StatusId]                INT             NOT NULL,
    [MembershipCardReference] NVARCHAR (MAX)  NULL,
    [SourceCurrency]          NVARCHAR (10)   NULL,
    [RecordStatusId]          INT             DEFAULT ((0)) NOT NULL,
    [Paid]                    BIT             CONSTRAINT [DF_CashbackTransaction_Paid] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_CashbackTransaction] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_CashbackTransaction_Status_RecordStatusId] FOREIGN KEY ([RecordStatusId]) REFERENCES [Exclusive].[Status] ([Id]),
    CONSTRAINT [FK_CashbackTransaction_Status_StatusId] FOREIGN KEY ([StatusId]) REFERENCES [Exclusive].[Status] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_CashbackTransaction_TransactionFile_TransactionFileId] FOREIGN KEY ([TransactionFileId]) REFERENCES [Staging].[TransactionFile] ([Id]) ON DELETE CASCADE
);

