using System.Collections.Generic;

namespace ExclusiveCard.Data.Models
{
    public class Country
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string PhonePrefix { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencySign { get; set; }
    }

    public class Countries
    {
        public static Dictionary<string, Country> CountriesList { get; } = new Dictionary<string, Country>
        {
            { "GB", new Country { Code = "GB", Name = "United Kingdom", PhonePrefix = "+44", CurrencyCode = "GBP", CurrencySign = "£" } },
            { "IN", new Country { Code = "IN", Name = "India", PhonePrefix = "+91", CurrencyCode = "INR", CurrencySign = "₹" } },
            { "US", new Country { Code = "US", Name = "United States", PhonePrefix = "+1", CurrencyCode = "USD", CurrencySign = "$" } },
            { "AE", new Country { Code = "AE", Name = "United Arab Emirates", PhonePrefix = "+971", CurrencyCode = "AED", CurrencySign = "د.إ;" } },
            { "AF", new Country { Code = "AF", Name = "Afghanistan", PhonePrefix = "+93", CurrencyCode = "", CurrencySign = "" } },
            { "AL", new Country { Code = "AL", Name = "Albania", PhonePrefix = "+355", CurrencyCode = "", CurrencySign = "" } },
            { "DZ", new Country { Code = "DZ", Name = "Algeria", PhonePrefix = "+213", CurrencyCode = "", CurrencySign = "" } },
            { "AS", new Country { Code = "AS", Name = "American Samoa", PhonePrefix = "+1 684", CurrencyCode = "", CurrencySign = "" } },
            { "AD", new Country { Code = "AD", Name = "Andorra", PhonePrefix = "+376", CurrencyCode = "", CurrencySign = "" } },
            { "AO", new Country { Code = "AO", Name = "Angola", PhonePrefix = "+244", CurrencyCode = "", CurrencySign = "" } },
            { "AI", new Country { Code = "AI", Name = "Anguilla", PhonePrefix = "+1 264", CurrencyCode = "", CurrencySign = "" } },
            { "AG", new Country { Code = "AG", Name = "Antigua and Barbuda", PhonePrefix = "+1 268", CurrencyCode = "", CurrencySign = "" } },
            { "AR", new Country { Code = "AR", Name = "Argentina", PhonePrefix = "+54", CurrencyCode = "", CurrencySign = "" } },
            { "AM", new Country { Code = "AM", Name = "Armenia", PhonePrefix = "+374", CurrencyCode = "", CurrencySign = "" } },
            { "AW", new Country { Code = "AW", Name = "Aruba", PhonePrefix = "+297", CurrencyCode = "", CurrencySign = "" } },
            { "AU", new Country { Code = "AU", Name = "Australia", PhonePrefix = "+61", CurrencyCode = "", CurrencySign = "" } },
            { "AT", new Country { Code = "AT", Name = "Austria", PhonePrefix = "+43", CurrencyCode = "", CurrencySign = "" } },
            { "AZ", new Country { Code = "AZ", Name = "Azerbaijan", PhonePrefix = "+994", CurrencyCode = "", CurrencySign = "" } },
            { "BS", new Country { Code = "BS", Name = "Bahamas", PhonePrefix = "+1 242", CurrencyCode = "", CurrencySign = "" } },
            { "BH", new Country { Code = "BH", Name = "Bahrain", PhonePrefix = "+973", CurrencyCode = "", CurrencySign = "" } },
            { "BD", new Country { Code = "BD", Name = "Bangladesh", PhonePrefix = "+880", CurrencyCode = "", CurrencySign = "" } },
            { "BB", new Country { Code = "BB", Name = "Barbados", PhonePrefix = "+1 246", CurrencyCode = "", CurrencySign = "" } },
            { "BY", new Country { Code = "BY", Name = "Belarus", PhonePrefix = "+375", CurrencyCode = "", CurrencySign = "" } },
            { "BE", new Country { Code = "BE", Name = "Belgium", PhonePrefix = "+32", CurrencyCode = "", CurrencySign = "" } },
            { "BZ", new Country { Code = "BZ", Name = "Belize", PhonePrefix = "+501", CurrencyCode = "", CurrencySign = "" } },
            { "BJ", new Country { Code = "BJ", Name = "Benin", PhonePrefix = "+229", CurrencyCode = "", CurrencySign = "" } },
            { "BM", new Country { Code = "BM", Name = "Bermuda", PhonePrefix = "+1 441", CurrencyCode = "", CurrencySign = "" } },
            { "BT", new Country { Code = "BT", Name = "Bhutan", PhonePrefix = "+975", CurrencyCode = "", CurrencySign = "" } },
            { "BA", new Country { Code = "BA", Name = "Bosnia and Herzegovina", PhonePrefix = "+387", CurrencyCode = "", CurrencySign = "" } },
            { "BW", new Country { Code = "BW", Name = "Botswana", PhonePrefix = "+267", CurrencyCode = "", CurrencySign = "" } },
            { "BR", new Country { Code = "BR", Name = "Brazil", PhonePrefix = "+55", CurrencyCode = "", CurrencySign = "" } },
            { "IO", new Country { Code = "IO", Name = "British Indian Ocean Territory", PhonePrefix = "+246", CurrencyCode = "", CurrencySign = "" } },
            { "BG", new Country { Code = "BG", Name = "Bulgaria", PhonePrefix = "+359", CurrencyCode = "", CurrencySign = "" } },
            { "BF", new Country { Code = "BF", Name = "Burkina Faso", PhonePrefix = "+226", CurrencyCode = "", CurrencySign = "" } },
            { "BI", new Country { Code = "BI", Name = "Burundi", PhonePrefix = "+257", CurrencyCode = "", CurrencySign = "" } },
            { "KH", new Country { Code = "KH", Name = "Cambodia", PhonePrefix = "+855", CurrencyCode = "", CurrencySign = "" } },
            { "CM", new Country { Code = "CM", Name = "Cameroon", PhonePrefix = "+237", CurrencyCode = "", CurrencySign = "" } },
            { "CA", new Country { Code = "CA", Name = "Canada", PhonePrefix = "+1", CurrencyCode = "", CurrencySign = "" } },
            { "CV", new Country { Code = "CV", Name = "Cape Verde", PhonePrefix = "+238", CurrencyCode = "", CurrencySign = "" } },
            { "KY", new Country { Code = "KY", Name = "Cayman Islands", PhonePrefix = "+1 345", CurrencyCode = "", CurrencySign = "" } },
            { "CF", new Country { Code = "CF", Name = "Central African Republic", PhonePrefix = "+236", CurrencyCode = "", CurrencySign = "" } },
            { "TD", new Country { Code = "TD", Name = "Chad", PhonePrefix = "+235", CurrencyCode = "", CurrencySign = "" } },
            { "CL", new Country { Code = "CL", Name = "Chile", PhonePrefix = "+56", CurrencyCode = "", CurrencySign = "" } },
            { "CN", new Country { Code = "CN", Name = "China", PhonePrefix = "+86", CurrencyCode = "", CurrencySign = "" } },
            { "CX", new Country { Code = "CX", Name = "Christmas Island", PhonePrefix = "+61", CurrencyCode = "", CurrencySign = "" } },
            { "CO", new Country { Code = "CO", Name = "Colombia", PhonePrefix = "+57", CurrencyCode = "", CurrencySign = "" } },
            { "KM", new Country { Code = "KM", Name = "Comoros", PhonePrefix = "+269", CurrencyCode = "", CurrencySign = "" } },
            { "CG", new Country { Code = "CG", Name = "Republic of the Congo", PhonePrefix = "+242", CurrencyCode = "", CurrencySign = "" } },
            { "CK", new Country { Code = "CK", Name = "Cook Islands", PhonePrefix = "+682", CurrencyCode = "", CurrencySign = "" } },
            { "CR", new Country { Code = "CR", Name = "Costa Rica", PhonePrefix = "+506", CurrencyCode = "", CurrencySign = "" } },
            { "HR", new Country { Code = "HR", Name = "Croatia", PhonePrefix = "+385", CurrencyCode = "", CurrencySign = "" } },
            { "CU", new Country { Code = "CU", Name = "Cuba", PhonePrefix = "+53", CurrencyCode = "", CurrencySign = "" } },
            { "CY", new Country { Code = "CY", Name = "Cyprus", PhonePrefix = "+537", CurrencyCode = "", CurrencySign = "" } },
            { "CZ", new Country { Code = "CZ", Name = "Czech Republic", PhonePrefix = "+420", CurrencyCode = "", CurrencySign = "" } },
            { "DK", new Country { Code = "DK", Name = "Denmark", PhonePrefix = "+45", CurrencyCode = "", CurrencySign = "" } },
            { "DJ", new Country { Code = "DJ", Name = "Djibouti", PhonePrefix = "+253", CurrencyCode = "", CurrencySign = "" } },
            { "DM", new Country { Code = "DM", Name = "Dominica", PhonePrefix = "+1 767", CurrencyCode = "", CurrencySign = "" } },
            { "DO", new Country { Code = "DO", Name = "Dominican Republic", PhonePrefix = "+1 849", CurrencyCode = "", CurrencySign = "" } },
            { "EC", new Country { Code = "EC", Name = "Ecuador", PhonePrefix = "+593", CurrencyCode = "", CurrencySign = "" } },
            { "EG", new Country { Code = "EG", Name = "Egypt", PhonePrefix = "+20", CurrencyCode = "", CurrencySign = "" } },
            { "SV", new Country { Code = "SV", Name = "El Salvador", PhonePrefix = "+503", CurrencyCode = "", CurrencySign = "" } },
            { "GQ", new Country { Code = "GQ", Name = "Equatorial Guinea", PhonePrefix = "+240", CurrencyCode = "", CurrencySign = "" } },
            { "ER", new Country { Code = "ER", Name = "Eritrea", PhonePrefix = "+291", CurrencyCode = "", CurrencySign = "" } },
            { "EE", new Country { Code = "EE", Name = "Estonia", PhonePrefix = "+372", CurrencyCode = "", CurrencySign = "" } },
            { "ET", new Country { Code = "ET", Name = "Ethiopia", PhonePrefix = "+251", CurrencyCode = "", CurrencySign = "" } },
            { "FO", new Country { Code = "FO", Name = "Faroe Islands", PhonePrefix = "+298", CurrencyCode = "", CurrencySign = "" } },
            { "FJ", new Country { Code = "FJ", Name = "Fiji", PhonePrefix = "+679", CurrencyCode = "", CurrencySign = "" } },
            { "FI", new Country { Code = "FI", Name = "Finland", PhonePrefix = "+358", CurrencyCode = "", CurrencySign = "" } },
            { "FR", new Country { Code = "FR", Name = "France", PhonePrefix = "+33", CurrencyCode = "", CurrencySign = "" } },
            { "GF", new Country { Code = "GF", Name = "French Guiana", PhonePrefix = "+594", CurrencyCode = "", CurrencySign = "" } },
            { "PF", new Country { Code = "PF", Name = "French Polynesia", PhonePrefix = "+689", CurrencyCode = "", CurrencySign = "" } },
            { "GA", new Country { Code = "GA", Name = "Gabon", PhonePrefix = "+241", CurrencyCode = "", CurrencySign = "" } },
            { "GM", new Country { Code = "GM", Name = "Gambia", PhonePrefix = "+220", CurrencyCode = "", CurrencySign = "" } },
            { "GE", new Country { Code = "GE", Name = "Georgia", PhonePrefix = "+995", CurrencyCode = "", CurrencySign = "" } },
            { "DE", new Country { Code = "DE", Name = "Germany", PhonePrefix = "+49", CurrencyCode = "", CurrencySign = "" } },
            { "GH", new Country { Code = "GH", Name = "Ghana", PhonePrefix = "+233", CurrencyCode = "", CurrencySign = "" } },
            { "GI", new Country { Code = "GI", Name = "Gibraltar", PhonePrefix = "+350", CurrencyCode = "", CurrencySign = "" } },
            { "GR", new Country { Code = "GR", Name = "Greece", PhonePrefix = "+30", CurrencyCode = "", CurrencySign = "" } },
            { "GL", new Country { Code = "GL", Name = "Greenland", PhonePrefix = "+299", CurrencyCode = "", CurrencySign = "" } },
            { "GD", new Country { Code = "GD", Name = "Grenada", PhonePrefix = "+1 473", CurrencyCode = "", CurrencySign = "" } },
            { "GP", new Country { Code = "GP", Name = "Guadeloupe", PhonePrefix = "+590", CurrencyCode = "", CurrencySign = "" } },
            { "GU", new Country { Code = "GU", Name = "Guam", PhonePrefix = "+1 671", CurrencyCode = "", CurrencySign = "" } },
            { "GT", new Country { Code = "GT", Name = "Guatemala", PhonePrefix = "+502", CurrencyCode = "", CurrencySign = "" } },
            { "GN", new Country { Code = "GN", Name = "Guinea", PhonePrefix = "+224", CurrencyCode = "", CurrencySign = "" } },
            { "GW", new Country { Code = "GW", Name = "Guinea-Bissau", PhonePrefix = "+245", CurrencyCode = "", CurrencySign = "" } },
            { "GY", new Country { Code = "GY", Name = "Guyana", PhonePrefix = "+595", CurrencyCode = "", CurrencySign = "" } },
            { "HT", new Country { Code = "HT", Name = "Haiti", PhonePrefix = "+509", CurrencyCode = "", CurrencySign = "" } },
            { "HN", new Country { Code = "HN", Name = "Honduras", PhonePrefix = "+504", CurrencyCode = "", CurrencySign = "" } },
            { "HU", new Country { Code = "HU", Name = "Hungary", PhonePrefix = "+36", CurrencyCode = "", CurrencySign = "" } },
            { "IS", new Country { Code = "IS", Name = "Iceland", PhonePrefix = "+354", CurrencyCode = "", CurrencySign = "" } },
            { "ID", new Country { Code = "ID", Name = "Indonesia", PhonePrefix = "+62", CurrencyCode = "", CurrencySign = "" } },
            { "IQ", new Country { Code = "IQ", Name = "Iraq", PhonePrefix = "+964", CurrencyCode = "", CurrencySign = "" } },
            { "IE", new Country { Code = "IE", Name = "Ireland", PhonePrefix = "+353", CurrencyCode = "", CurrencySign = "" } },
            { "IL", new Country { Code = "IL", Name = "Israel", PhonePrefix = "+972", CurrencyCode = "", CurrencySign = "" } },
            { "IT", new Country { Code = "IT", Name = "Italy", PhonePrefix = "+39", CurrencyCode = "", CurrencySign = "" } },
            { "JM", new Country { Code = "JM", Name = "Jamaica", PhonePrefix = "+1 876", CurrencyCode = "", CurrencySign = "" } },
            { "JP", new Country { Code = "JP", Name = "Japan", PhonePrefix = "+81", CurrencyCode = "", CurrencySign = "" } },
            { "JO", new Country { Code = "JO", Name = "Jordan", PhonePrefix = "+962", CurrencyCode = "", CurrencySign = "" } },
            { "KZ", new Country { Code = "KZ", Name = "Kazakhstan", PhonePrefix = "+7", CurrencyCode = "", CurrencySign = "" } },
            { "KE", new Country { Code = "KE", Name = "Kenya", PhonePrefix = "+254", CurrencyCode = "", CurrencySign = "" } },
            { "KI", new Country { Code = "KI", Name = "Kiribati", PhonePrefix = "+686", CurrencyCode = "", CurrencySign = "" } },
            { "KW", new Country { Code = "KW", Name = "Kuwait", PhonePrefix = "+965", CurrencyCode = "", CurrencySign = "" } },
            { "KG", new Country { Code = "KG", Name = "Kyrgyzstan", PhonePrefix = "+996", CurrencyCode = "", CurrencySign = "" } },
            { "LV", new Country { Code = "LV", Name = "Latvia", PhonePrefix = "+371", CurrencyCode = "", CurrencySign = "" } },
            { "LB", new Country { Code = "LB", Name = "Lebanon", PhonePrefix = "+961", CurrencyCode = "", CurrencySign = "" } },
            { "LS", new Country { Code = "LS", Name = "Lesotho", PhonePrefix = "+266", CurrencyCode = "", CurrencySign = "" } },
            { "LR", new Country { Code = "LR", Name = "Liberia", PhonePrefix = "+231", CurrencyCode = "", CurrencySign = "" } },
            { "LI", new Country { Code = "LI", Name = "Liechtenstein", PhonePrefix = "+423", CurrencyCode = "", CurrencySign = "" } },
            { "LT", new Country { Code = "LT", Name = "Lithuania", PhonePrefix = "+370", CurrencyCode = "", CurrencySign = "" } },
            { "LU", new Country { Code = "LU", Name = "Luxembourg", PhonePrefix = "+352", CurrencyCode = "", CurrencySign = "" } },
            { "MG", new Country { Code = "MG", Name = "Madagascar", PhonePrefix = "+261", CurrencyCode = "", CurrencySign = "" } },
            { "MW", new Country { Code = "MW", Name = "Malawi", PhonePrefix = "+265", CurrencyCode = "", CurrencySign = "" } },
            { "MY", new Country { Code = "MY", Name = "Malaysia", PhonePrefix = "+60", CurrencyCode = "", CurrencySign = "" } },
            { "MV", new Country { Code = "MV", Name = "Maldives", PhonePrefix = "+960", CurrencyCode = "", CurrencySign = "" } },
            { "ML", new Country { Code = "ML", Name = "Mali", PhonePrefix = "+223", CurrencyCode = "", CurrencySign = "" } },
            { "MT", new Country { Code = "MT", Name = "Malta", PhonePrefix = "+356", CurrencyCode = "", CurrencySign = "" } },
            { "MH", new Country { Code = "MH", Name = "Marshall Islands", PhonePrefix = "+692", CurrencyCode = "", CurrencySign = "" } },
            { "MQ", new Country { Code = "MQ", Name = "Martinique", PhonePrefix = "+596", CurrencyCode = "", CurrencySign = "" } },
            { "MR", new Country { Code = "MR", Name = "Mauritania", PhonePrefix = "+222", CurrencyCode = "", CurrencySign = "" } },
            { "MU", new Country { Code = "MU", Name = "Mauritius", PhonePrefix = "+230", CurrencyCode = "", CurrencySign = "" } },
            { "YT", new Country { Code = "YT", Name = "Mayotte", PhonePrefix = "+262", CurrencyCode = "", CurrencySign = "" } },
            { "MX", new Country { Code = "MX", Name = "Mexico", PhonePrefix = "+52", CurrencyCode = "", CurrencySign = "" } },
            { "MC", new Country { Code = "MC", Name = "Monaco", PhonePrefix = "+377", CurrencyCode = "", CurrencySign = "" } },
            { "MN", new Country { Code = "MN", Name = "Mongolia", PhonePrefix = "+976", CurrencyCode = "", CurrencySign = "" } },
            { "ME", new Country { Code = "ME", Name = "Montenegro", PhonePrefix = "+382", CurrencyCode = "", CurrencySign = "" } },
            { "MS", new Country { Code = "MS", Name = "Montserrat", PhonePrefix = "+1 664", CurrencyCode = "", CurrencySign = "" } },
            { "MA", new Country { Code = "MA", Name = "Morocco", PhonePrefix = "+212", CurrencyCode = "", CurrencySign = "" } },
            { "MM", new Country { Code = "MM", Name = "Myanmar", PhonePrefix = "+95", CurrencyCode = "", CurrencySign = "" } },
            { "NA", new Country { Code = "NA", Name = "Namibia", PhonePrefix = "+264", CurrencyCode = "", CurrencySign = "" } },
            { "NR", new Country { Code = "NR", Name = "Nauru", PhonePrefix = "+674", CurrencyCode = "", CurrencySign = "" } },
            { "NP", new Country { Code = "NP", Name = "Nepal", PhonePrefix = "+977", CurrencyCode = "", CurrencySign = "" } },
            { "NL", new Country { Code = "NL", Name = "Netherlands", PhonePrefix = "+31", CurrencyCode = "", CurrencySign = "" } },
            { "AN", new Country { Code = "AN", Name = "Netherlands Antilles", PhonePrefix = "+599", CurrencyCode = "", CurrencySign = "" } },
            { "NC", new Country { Code = "NC", Name = "New Caledonia", PhonePrefix = "+687", CurrencyCode = "", CurrencySign = "" } },
            { "NZ", new Country { Code = "NZ", Name = "New Zealand", PhonePrefix = "+64", CurrencyCode = "", CurrencySign = "" } },
            { "NI", new Country { Code = "NI", Name = "Nicaragua", PhonePrefix = "+505", CurrencyCode = "", CurrencySign = "" } },
            { "NE", new Country { Code = "NE", Name = "Niger", PhonePrefix = "+227", CurrencyCode = "", CurrencySign = "" } },
            { "NG", new Country { Code = "NG", Name = "Nigeria", PhonePrefix = "+234", CurrencyCode = "", CurrencySign = "" } },
            { "NU", new Country { Code = "NU", Name = "Niue", PhonePrefix = "+683", CurrencyCode = "", CurrencySign = "" } },
            { "NF", new Country { Code = "NF", Name = "Norfolk Island", PhonePrefix = "+672", CurrencyCode = "", CurrencySign = "" } },
            { "MP", new Country { Code = "MP", Name = "Northern Mariana Islands", PhonePrefix = "+1 670", CurrencyCode = "", CurrencySign = "" } },
            { "NO", new Country { Code = "NO", Name = "Norway", PhonePrefix = "+47", CurrencyCode = "", CurrencySign = "" } },
            { "OM", new Country { Code = "OM", Name = "Oman", PhonePrefix = "+968", CurrencyCode = "", CurrencySign = "" } },
            { "PK", new Country { Code = "PK", Name = "Pakistan", PhonePrefix = "+92", CurrencyCode = "", CurrencySign = "" } },
            { "PW", new Country { Code = "PW", Name = "Palau", PhonePrefix = "+680", CurrencyCode = "", CurrencySign = "" } },
            { "PA", new Country { Code = "PA", Name = "Panama", PhonePrefix = "+507", CurrencyCode = "", CurrencySign = "" } },
            { "PG", new Country { Code = "PG", Name = "Papua New Guinea", PhonePrefix = "+675", CurrencyCode = "", CurrencySign = "" } },
            { "PY", new Country { Code = "PY", Name = "Paraguay", PhonePrefix = "+595", CurrencyCode = "", CurrencySign = "" } },
            { "PE", new Country { Code = "PE", Name = "Peru", PhonePrefix = "+51", CurrencyCode = "", CurrencySign = "" } },
            { "PH", new Country { Code = "PH", Name = "Philippines", PhonePrefix = "+63", CurrencyCode = "", CurrencySign = "" } },
            { "PL", new Country { Code = "PL", Name = "Poland", PhonePrefix = "+48", CurrencyCode = "", CurrencySign = "" } },
            { "PT", new Country { Code = "PT", Name = "Portugal", PhonePrefix = "+351", CurrencyCode = "", CurrencySign = "" } },
            { "PR", new Country { Code = "PR", Name = "Puerto Rico", PhonePrefix = "+1 939", CurrencyCode = "", CurrencySign = "" } },
            { "QA", new Country { Code = "QA", Name = "Qatar", PhonePrefix = "+974", CurrencyCode = "", CurrencySign = "" } },
            { "RO", new Country { Code = "RO", Name = "Romania", PhonePrefix = "+40", CurrencyCode = "", CurrencySign = "" } },
            { "RW", new Country { Code = "RW", Name = "Rwanda", PhonePrefix = "+250", CurrencyCode = "", CurrencySign = "" } },
            { "WS", new Country { Code = "WS", Name = "Samoa", PhonePrefix = "+685", CurrencyCode = "", CurrencySign = "" } },
            { "SM", new Country { Code = "SM", Name = "San Marino", PhonePrefix = "+378", CurrencyCode = "", CurrencySign = "" } },
            { "SA", new Country { Code = "SA", Name = "Saudi Arabia", PhonePrefix = "+966", CurrencyCode = "", CurrencySign = "" } },
            { "SN", new Country { Code = "SN", Name = "Senegal", PhonePrefix = "+221", CurrencyCode = "", CurrencySign = "" } },
            { "RS", new Country { Code = "RS", Name = "Serbia", PhonePrefix = "+381", CurrencyCode = "", CurrencySign = "" } },
            { "SC", new Country { Code = "SC", Name = "Seychelles", PhonePrefix = "+248", CurrencyCode = "", CurrencySign = "" } },
            { "SL", new Country { Code = "SL", Name = "Sierra Leone", PhonePrefix = "+232", CurrencyCode = "", CurrencySign = "" } },
            { "SG", new Country { Code = "SG", Name = "Singapore", PhonePrefix = "+65", CurrencyCode = "", CurrencySign = "" } },
            { "SK", new Country { Code = "SK", Name = "Slovakia", PhonePrefix = "+421", CurrencyCode = "", CurrencySign = "" } },
            { "SI", new Country { Code = "SI", Name = "Slovenia", PhonePrefix = "+386", CurrencyCode = "", CurrencySign = "" } },
            { "SB", new Country { Code = "SB", Name = "Solomon Islands", PhonePrefix = "+677", CurrencyCode = "", CurrencySign = "" } },
            { "ZA", new Country { Code = "ZA", Name = "South Africa", PhonePrefix = "+27", CurrencyCode = "", CurrencySign = "" } },
            { "GS", new Country { Code = "GS", Name = "South Georgia and the South Sandwich Islands", PhonePrefix = "+500", CurrencyCode = "", CurrencySign = "" } },
            { "ES", new Country { Code = "ES", Name = "Spain", PhonePrefix = "+34", CurrencyCode = "", CurrencySign = "" } },
            { "LK", new Country { Code = "LK", Name = "Sri Lanka", PhonePrefix = "+94", CurrencyCode = "", CurrencySign = "" } },
            { "SD", new Country { Code = "SD", Name = "Sudan", PhonePrefix = "+249", CurrencyCode = "", CurrencySign = "" } },
            { "SR", new Country { Code = "SR", Name = "Suriname", PhonePrefix = "+597", CurrencyCode = "", CurrencySign = "" } },
            { "SZ", new Country { Code = "SZ", Name = "Swaziland", PhonePrefix = "+268", CurrencyCode = "", CurrencySign = "" } },
            { "SE", new Country { Code = "SE", Name = "Sweden", PhonePrefix = "+46", CurrencyCode = "", CurrencySign = "" } },
            { "CH", new Country { Code = "CH", Name = "Switzerland", PhonePrefix = "+41", CurrencyCode = "", CurrencySign = "" } },
            { "TJ", new Country { Code = "TJ", Name = "Tajikistan", PhonePrefix = "+992", CurrencyCode = "", CurrencySign = "" } },
            { "TH", new Country { Code = "TH", Name = "Thailand", PhonePrefix = "+66", CurrencyCode = "", CurrencySign = "" } },
            { "TG", new Country { Code = "TG", Name = "Togo", PhonePrefix = "+228", CurrencyCode = "", CurrencySign = "" } },
            { "TK", new Country { Code = "TK", Name = "Tokelau", PhonePrefix = "+690", CurrencyCode = "", CurrencySign = "" } },
            { "TO", new Country { Code = "TO", Name = "Tonga", PhonePrefix = "+676", CurrencyCode = "", CurrencySign = "" } },
            { "TT", new Country { Code = "TT", Name = "Trinidad and Tobago", PhonePrefix = "+1 868", CurrencyCode = "", CurrencySign = "" } },
            { "TN", new Country { Code = "TN", Name = "Tunisia", PhonePrefix = "+216", CurrencyCode = "", CurrencySign = "" } },
            { "TR", new Country { Code = "TR", Name = "Turkey", PhonePrefix = "+90", CurrencyCode = "", CurrencySign = "" } },
            { "TM", new Country { Code = "TM", Name = "Turkmenistan", PhonePrefix = "+993", CurrencyCode = "", CurrencySign = "" } },
            { "TC", new Country { Code = "TC", Name = "Turks and Caicos Islands", PhonePrefix = "+1 649", CurrencyCode = "", CurrencySign = "" } },
            { "TV", new Country { Code = "TV", Name = "Tuvalu", PhonePrefix = "+688", CurrencyCode = "", CurrencySign = "" } },
            { "UG", new Country { Code = "UG", Name = "Uganda", PhonePrefix = "+256", CurrencyCode = "", CurrencySign = "" } },
            { "UA", new Country { Code = "UA", Name = "Ukraine", PhonePrefix = "+380", CurrencyCode = "", CurrencySign = "" } },
            { "UY", new Country { Code = "UY", Name = "Uruguay", PhonePrefix = "+598", CurrencyCode = "", CurrencySign = "" } },
            { "UZ", new Country { Code = "UZ", Name = "Uzbekistan", PhonePrefix = "+998", CurrencyCode = "", CurrencySign = "" } },
            { "VU", new Country { Code = "VU", Name = "Vanuatu", PhonePrefix = "+678", CurrencyCode = "", CurrencySign = "" } },
            { "WF", new Country { Code = "WF", Name = "Wallis and Futuna", PhonePrefix = "+681", CurrencyCode = "", CurrencySign = "" } },
            { "YE", new Country { Code = "YE", Name = "Yemen", PhonePrefix = "+967", CurrencyCode = "", CurrencySign = "" } },
            { "ZM", new Country { Code = "ZM", Name = "Zambia", PhonePrefix = "+260", CurrencyCode = "", CurrencySign = "" } },
            { "ZW", new Country { Code = "ZW", Name = "Zimbabwe", PhonePrefix = "+263", CurrencyCode = "", CurrencySign = "" } },
            { "AQ", new Country { Code = "AQ", Name = "Antarctica", PhonePrefix = "+672", CurrencyCode = "", CurrencySign = "" } },
            { "BO", new Country { Code = "BO", Name = "Bolivia", PhonePrefix = "+591", CurrencyCode = "", CurrencySign = "" } },
            { "BN", new Country { Code = "BN", Name = "Brunei Darussalam", PhonePrefix = "+673", CurrencyCode = "", CurrencySign = "" } },
            { "CC", new Country { Code = "CC", Name = "Cocos Islands", PhonePrefix = "+61", CurrencyCode = "", CurrencySign = "" } },
            { "CD", new Country { Code = "CD", Name = "Democratic Republic of the Congo", PhonePrefix = "+243", CurrencyCode = "", CurrencySign = "" } },
            { "CI", new Country { Code = "CI", Name = "Ivory Coast", PhonePrefix = "+225", CurrencyCode = "", CurrencySign = "" } },
            { "FK", new Country { Code = "FK", Name = "Falkland Islands", PhonePrefix = "+500", CurrencyCode = "", CurrencySign = "" } },
            { "GG", new Country { Code = "GG", Name = "Guernsey", PhonePrefix = "+44 1481", CurrencyCode = "", CurrencySign = "" } },
            { "VA", new Country { Code = "VA", Name = "Vatican", PhonePrefix = "+379", CurrencyCode = "", CurrencySign = "" } },
            { "HK", new Country { Code = "HK", Name = "Hong Kong", PhonePrefix = "+852", CurrencyCode = "", CurrencySign = "" } },
            { "IR", new Country { Code = "IR", Name = "Iran", PhonePrefix = "+98", CurrencyCode = "", CurrencySign = "" } },
            { "IM", new Country { Code = "IM", Name = "Isle of Man", PhonePrefix = "+44 1624", CurrencyCode = "", CurrencySign = "" } },
            { "JE", new Country { Code = "JE", Name = "Jersey", PhonePrefix = "+44 1534", CurrencyCode = "", CurrencySign = "" } },
            { "KP", new Country { Code = "KP", Name = "North Korea", PhonePrefix = "+850", CurrencyCode = "", CurrencySign = "" } },
            { "KR", new Country { Code = "KR", Name = "South Korea", PhonePrefix = "+82", CurrencyCode = "", CurrencySign = "" } },
            { "LA", new Country { Code = "LA", Name = "Laos", PhonePrefix = "+856", CurrencyCode = "", CurrencySign = "" } },
            { "LY", new Country { Code = "LY", Name = "Libya", PhonePrefix = "+218", CurrencyCode = "", CurrencySign = "" } },
            { "MO", new Country { Code = "MO", Name = "Macao", PhonePrefix = "+853", CurrencyCode = "", CurrencySign = "" } },
            { "MK", new Country { Code = "MK", Name = "Macedonia", PhonePrefix = "+389", CurrencyCode = "", CurrencySign = "" } },
            { "FM", new Country { Code = "FM", Name = "Micronesia", PhonePrefix = "+691", CurrencyCode = "", CurrencySign = "" } },
            { "MD", new Country { Code = "MD", Name = "Moldova", PhonePrefix = "+373", CurrencyCode = "", CurrencySign = "" } },
            { "MZ", new Country { Code = "MZ", Name = "Mozambique", PhonePrefix = "+258", CurrencyCode = "", CurrencySign = "" } },
            { "PS", new Country { Code = "PS", Name = "Palestine", PhonePrefix = "+970", CurrencyCode = "", CurrencySign = "" } },
            { "PN", new Country { Code = "PN", Name = "Pitcairn", PhonePrefix = "+872", CurrencyCode = "", CurrencySign = "" } },
            { "RE", new Country { Code = "RE", Name = "Reunion", PhonePrefix = "+262", CurrencyCode = "", CurrencySign = "" } },
            { "RU", new Country { Code = "RU", Name = "Russia", PhonePrefix = "+7", CurrencyCode = "", CurrencySign = "" } },
            { "BL", new Country { Code = "BL", Name = "Saint Barthelemy", PhonePrefix = "+590", CurrencyCode = "", CurrencySign = "" } },
            { "SH", new Country { Code = "SH", Name = "Saint Helena", PhonePrefix = "+290", CurrencyCode = "", CurrencySign = "" } },
            { "KN", new Country { Code = "KN", Name = "Saint Kitts and Nevis", PhonePrefix = "+1 869", CurrencyCode = "", CurrencySign = "" } },
            { "LC", new Country { Code = "LC", Name = "Saint Lucia", PhonePrefix = "+1 758", CurrencyCode = "", CurrencySign = "" } },
            { "MF", new Country { Code = "MF", Name = "Saint Martin", PhonePrefix = "+590", CurrencyCode = "", CurrencySign = "" } },
            { "PM", new Country { Code = "PM", Name = "Saint Pierre and Miquelon", PhonePrefix = "+508", CurrencyCode = "", CurrencySign = "" } },
            { "VC", new Country { Code = "VC", Name = "Saint Vincent and the Grenadines", PhonePrefix = "+1 784", CurrencyCode = "", CurrencySign = "" } },
            { "ST", new Country { Code = "ST", Name = "Sao Tome and Principe", PhonePrefix = "+239", CurrencyCode = "", CurrencySign = "" } },
            { "SO", new Country { Code = "SO", Name = "Somalia", PhonePrefix = "+252", CurrencyCode = "", CurrencySign = "" } },
            { "SJ", new Country { Code = "SJ", Name = "Svalbard and Jan Mayen", PhonePrefix = "+47", CurrencyCode = "", CurrencySign = "" } },
            { "SY", new Country { Code = "SY", Name = "Syria", PhonePrefix = "+963", CurrencyCode = "", CurrencySign = "" } },
            { "TW", new Country { Code = "TW", Name = "Taiwan", PhonePrefix = "+886", CurrencyCode = "", CurrencySign = "" } },
            { "TZ", new Country { Code = "TZ", Name = "Tanzania, United Republic of", PhonePrefix = "+255", CurrencyCode = "", CurrencySign = "" } },
            { "TL", new Country { Code = "TL", Name = "East Timor", PhonePrefix = "+670", CurrencyCode = "", CurrencySign = "" } },
            { "VE", new Country { Code = "VE", Name = "Venezuela", PhonePrefix = "+58", CurrencyCode = "", CurrencySign = "" } },
            { "VN", new Country { Code = "VN", Name = "Vietnam", PhonePrefix = "+84", CurrencyCode = "", CurrencySign = "" } },
            { "VG", new Country { Code = "VG", Name = "British Virgin Islands", PhonePrefix = "+1 284", CurrencyCode = "", CurrencySign = "" } },
            { "VI", new Country { Code = "VI", Name = "U.S. Virgin Islands", PhonePrefix = "+1 340", CurrencyCode = "", CurrencySign = "" } }
        };
    }
}