CREATE TABLE [CMS].[WhitelabelSettings] (
    [Id]            INT            IDENTITY (1, 1) NOT NULL,
    [Name]          NVARCHAR (255) NULL,
    [DisplayName]   NVARCHAR (255) NULL,
    [URL]           NVARCHAR (100) NULL,
    [Slug]          NVARCHAR (255) NULL,
    [CompanyNumber] NVARCHAR (10)  NULL,
    [CSSFile]       NVARCHAR (255) NULL,
    [Logo]          NVARCHAR (255) NULL,
    [ClaimsEmail]   NVARCHAR (100) NULL,
    [HelpEmail]     NVARCHAR (100) NULL,
    [MainEmail]     NVARCHAR (100) NULL,
    [Address]       NVARCHAR (MAX) NULL,
    [CardName]      NVARCHAR (255) NULL,
    [PrivacyPolicy] NVARCHAR(512) NULL, 
    [Terms] NVARCHAR(512) NULL, 
    [SiteType] INT NULL, 
    [CharityName] NVARCHAR(255) NULL, 
    [CharityUrl] NVARCHAR(512) NULL, 
    [NewsletterLogo] NVARCHAR(255) NULL, 
    [SiteOwnerId] INT NULL, 
    [RegistrationUrl] NVARCHAR(512) NULL,
    [IsRegional] BIT            DEFAULT ((0)) NOT NULL,
    [DefaultRegion] INT NOT NULL DEFAULT 0, 
    CONSTRAINT [PK_WhitelabelSettings] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_WhitelabelSettings_SiteOwner_SiteOwnerId] FOREIGN KEY ([SiteOwnerId]) REFERENCES [CMS].[SiteOwner] ([Id]),

);

